### ISSUE TITLE
ISRC codes generated are wrong

### ISSUE THREAD

**Issue by CyberbobGR** [imPRAGMA/VEVODL#1]
Hi, i don't know why, but when you search the program finds ISRC codes that are not compatible with VEVO. For example searching for Iggy Azalea - Savior, it will generate USUM71800771 which is not available on the VEVO servers. However if you directly input USUV71800288 as ISRC it will correctly download the file.

**Comment by imPRAGMA** [comment]
This isn't a bug, how it finds ISRC codes is it simply searches a database the artist and song name, meaning it will list literally every single release. You basically just have to trial and error each code to find one thats on VEVO's servers. First 2 characters = country code, next 3 = identity codes.
UV7 and IV2 are typically ones that are on VEVO but not all the time, i'm not sure if VEVO uses any other identity code which is why it doesnt filter the list to only show codes on the server, as there's no way to tell.

**Comment by CyberbobGR** [comment]
Oh, i see. Thank you for the extremely fast reply. I haven't found a way yet to find the right ISRC codes, but i will keep looking.

**Comment by imPRAGMA** [comment]
As I said, its pretty much just guess work, read the release versions, they usually say stuff like remix or such, those wouldnt typically be on VEVO's server.

**Comment by imPRAGMA** [comment]
P.S. Reminder that you could do your search then just press DPAD Up to attempt to download literally every ISRC for that search

**Comment by CyberbobGR** [comment]
I did the DPAD up thing, but all codes were not found on VEVO's servers. 
The non remix version of my example song above shows this ISRC on the program: USUM71800771
The right ISRC that will download the video is USUV71800288.
So if we replace the M character with V and search for the 3 last digits from 001 to 999 theoritically will find the right code and download. Is there any way to set a range of ISRCs for the program to try and download?
